// Generated by CoffeeScript 1.8.0

/*
 * Password.js | coffee
 *
 * Ayuda al usuario a cambiar la contraseña de inicio de sesión de
 * su cuenta por una personalizada.
 *
 * Out: Object { oldPass, newPass }
 * In: Object { success, message }
 */

(function() {
  $(document).ready(function() {
    return $('#pass-form').on('submit', function(event) {
      var form_data;
      event.preventDefault();
      $('.alert').remove();
      if ($('#new').val() !== $('#confirm').val()) {
        return $('#pass-form').prepend('<div class="alert alert-warning"><button type="button" class="close" data-dismiss="alert"> <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> <b>Error:</b> La nueva contraseña debe coincidir</div>');
      } else {
        form_data = {
          oldPass: $('#old').val(),
          newPass: $('#new').val()
        };
        console.log(form_data);
        return $.ajax({
          url: '/newPass',
          method: 'POST',
          data: form_data,
          success: function(data, textStatus, jqXHR) {
            var response;
            response = JSON.parse(jqXHR.responseText);
            if (response.success === true) {
              $('#pass-form').prepend('<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert"> <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> <b>Éxito:</b> MSJ</div>'.replace('MSJ', response.message));
              $('#old').val('');
              $('#new').val('');
              $('#confirm').val('');
            } else {
              $('#pass-form').prepend('<div class="alert alert-warning"><button type="button" class="close" data-dismiss="alert"> <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> <b>Error:</b> MSJ</div>'.replace('MSJ', response.message));
              $('#old').val('');
              $('#new').val('');
              $('#confirm').val('');
            }
          },
          error: function(data, textStatus, jqXHR) {
            $('#pass-form').prepend('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert"> <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> <b>Error:</b> No hay conexión con la aplicación o la respuesta está tardando demasiado. Por favor pide ayuda o reintenta enviar el formulario.</div>');
            $('#old').val('');
            $('#new').val('');
            $('#confirm').val('');
          }
        });
      }
    });
  });

}).call(this);
