// Generated by CoffeeScript 1.8.0

/*
 *  apiRouter
 *
 * Router de Express.js que recibe y procesa todas las peticiones
 * hechas desde Backbone hacia la aplicación en la ruta montada,
 * actualmente '/datos.json'
 *
 * El Router crea, actualiza, borra y manda toda la información a
 * la aplicación Backbone en el frontend para interactuar con el
 * usuario.
 *
 * Con los datos que no estén vigentes no haremos nada por el momento,
 * pero queda a reserva revisarlos para ver cuáles han sido borrados.
 */
var Datos, express, router;

express = require('express');

router = express.Router();

Datos = require('./models/Datos');

router.get('/', function(req, res) {
  return Datos.find({
    Vigente: true
  }).sort({
    Number: -1
  }).exec(function(err, documents) {
    if (err) {
      return res.json({
        success: false,
        message: 'Hubo un error con la base de datos. Pide ayuda.'
      });
    } else {
      return res.json(documents);
    }
  });
});

router.post('/', function(req, res) {
  if (parseInt(req.body.Number) > 0 && (req.body.Number !== null)) {
    return Datos.findOne({
      Number: req.body.Number,
      Vigente: true
    }, function(err, doc) {
      var muestra;
      if (err) {
        console.log("Hubo un error con la base de datos: " + err);
        res.json({
          success: false,
          message: "Hubo un error con la base de datos: " + err
        });
      }
      if (doc) {
        console.log("Ya se encuentra un registro de esta muestra");
        return res.json({
          success: false,
          message: "Ya se encuentra un registro de esta muestra"
        });
      } else {
        muestra = new Datos({
          Number: req.body.Number,
          Gender: req.body.Gender,
          Color: req.body.Color,
          Tinte: req.body.Tinte
        });
        return muestra.save(function(saveErr) {
          if (saveErr) {
            console.log("Hubo un error al guardar la información: " + saveErr);
            return res.json({
              success: false,
              message: "No se puede guardar la información. Pide ayuda."
            });
          } else {
            return res.json({
              success: true,
              message: "La información se guardó correctamente",
              model: muestra
            });
          }
        });
      }
    });
  } else {
    return res.json({
      success: false,
      message: "Debes introducir un número válido para la muestra."
    });
  }
});

router.put('/:id', function(req, res) {
  console.log(req.params.id);
  return Datos.findOne({
    _id: id
  }, function(err, doc) {
    return res.json({
      success: true,
      message: "Completada la operación"
    });
  });
});

router["delete"]('/:id', function(req, res) {
  console.log("Anulando el registro con el ID " + req.params.id);
  return Datos.findOne({
    _id: req.params.id
  }, function(err, registro) {
    if (err) {
      console.log("Ocurrió un error al bucar el registro " + req.params.id + ": " + err);
      res.json({
        success: false,
        message: 'Error interno, reintenta por favor.'
      });
    }
    if (registro) {
      registro.Vigente = false;
      return registro.save(function(saveErr) {
        if (saveErr) {
          return res.json({
            success: false,
            message: "No se puede guardar el cambio en la base de datos, por favor pide ayuda."
          });
        } else {
          return res.json({
            success: true,
            message: "El registro se anuló satisfactoriamente."
          });
        }
      });
    } else {
      return res.json({
        success: false,
        message: "No podemos encontrar el registro que quieres anular, por favor pide ayuda."
      });
    }
  });
});

router.use(function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    return res.json({
      success: false,
      message: 'Debes iniciar sesión para continuar'
    });
  }
});

module.exports = router;
