// Generated by CoffeeScript 1.8.0
var Datos, User, isLoggedIn, isSessioned;

User = require('./models/User');

Datos = require('./models/Datos');

module.exports = function(app, passport) {
  app.get('/', function(req, res) {
    if (req.isAuthenticated()) {
      return res.redirect('/dashboard');
    } else {
      return res.render('index.jade');
    }
  });
  app.get('/dashboard', isLoggedIn, function(req, res) {
    return res.render('dashboard.jade', req.user);
  });
  app.post('/login', passport.authenticate('local-login', {
    successRedirect: '/dashboard',
    failureRedirect: '/'
  }));
  app.get('/datos', isLoggedIn, function(req, res) {
    return res.render('datos.jade', req.user);
  });
  return app.get('/logout', isLoggedIn, function(req, res) {
    req.logout();
    return res.redirect('/');
  });
};

isLoggedIn = function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    return res.redirect('/login');
  }
};

isSessioned = function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    return res.json({
      error: "Debes iniciar sesión para continuar."
    });
  }
};
